# Conceptos basicos


Hablar de inteligencia artificial es un concepto bastante amplio que agrupa varios tipos de tecnología. Los primeros tipos de IA consisten es simular una serie de tareas intelectuales mediante el establecimiento o algortimia de todas las reglas que programan una tarea.

El Machine learning consiste en un tipo de IA que es capaz de generar las propias dentro del sistema problema dándole datos y las supuestas respuestas, de tal forma que algoritimicamente podemos predecirlas.

Las Redes Neuronales, son un tipo de mecanismo usado en ML en el cual añadimos mas sets de reglas (funciones, aplicaciones) entre unos inputs y unos outputs. Es un tipo de estructura de extracción de información en varias fases.






Para ML vamos a utilizar una libreria que se basa en el uso de arrays como tensores, y todas las matematicas chulis que podemos hacer con ellos.
Recordemos que no tenemos ni idea de lo que es un tensor, más alla de una cosa que se transforma como un tensor, así que para esta tarea en concreto, vamos a considerarlos una generalización de vectores en n-dim.

En TensorFlow, hay una variable /objeto concreta que es el tensor. La libreria funciona mediante la relación con grafos de esos objetos.

Los tensores pueden almacenar distintos tipos de datos en sus componentes, y tomar distintos valores en sus dimensiones.

Cualquier variable creada dentro de la libreria de TensorFlow es un tensor que puede tener estas caracteristicas



 

In [2]:
import tensorflow as tf 


In [4]:
string = tf.Variable("string",tf.string)
number = tf.Variable(12,tf.int16)
floating= tf.Variable(3.5, tf.float64)

La dimension del tensor creado de esta forma es la automatica según la libreria, pero podemos controlar la dimension del escalar en su creación utilizando listas como inputs.

In [6]:
escalar = tf.Variable(["cosastring","cosastring2"],tf.string)
matriz = tf.Variable([["primera cosa","segunda cosa"],["otra cosa","otrascosas"]],tf.string)

Además pudemos utilizar la función de la libreria .rank() para saber la dimensión de un tensor.

In [7]:
tf.rank(matriz)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

El numero de elementos distribuidos por la forma del tensor es la shape del tensor, se calcula como un método de los objetos tipo tf.

In [9]:
escalar.shape

TensorShape([2])

La respuesta son el numero de filas como [] con el numero de elementos en su interior


Podemos cambiar la forma de los tensores jugando con los metodos de tf como reshape y otros, siempre teniendo en cuenta que el numero de elementos en transformaciones ha de permanecer constante.

In [10]:
tensor1 =tf.ones([1,2,3]) #tf.ones() crea una forma con 1,2,3 lleno de unos (1 lista con dos listas con 3 elementos cada una, ese elemento es el uno)
tensor2=tf.reshape(tensor1,[2,3,1]) #con este metodo transformamos un tensor objetivo en el orden que hemos descrito ( dos listas con tres listas con 1 elemento cada una)
tensor3= tf.reshape(tensor2,[3,-1]) #hacemos lo mismo pero utilizando el atajo-1, esto lo que hace es que la librería calcula el tamaño de la dimensión en ese lugar de forma automatica (3 listas con todos los elementos repartidas de forma equitativa, en este caso 2 por lista)


In [12]:
print(tensor1)
print(tensor2)
print(tensor3)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Tipos de tensores

Los tipos más comunes de tensores (creado utilizando funciones del paquete tf.) son 

- Variable
- Constant
- Placeholder 
- SparseTensor 

Siendo todos, menos Variable, objetos inmutables.

Vamos a hacer un miniejemplo de transformaciones

In [13]:
t = tf.zeros([5,5,5,5,5])

In [15]:
print(t)

tf.Tensor(
[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
   

In [17]:
t = tf.reshape(t,[-1])
print(t)

tf.Tensor([0. 0. 0. ... 0. 0. 0.], shape=(3125,), dtype=float32)


In [21]:
t =tf.reshape(t, [5,-1])
print(t)

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(5, 625), dtype=float32)


# Algoritmos nucleares de TensorFlow

Al final del dia, ML no es más que una forma automatizada de reconocer patrones. Los principales algoritmos son: 

- Regresión lineal.
- Clasificación
- Clustering
- Modelos de Markkov


En todo momento vamos a estar usando grupos de datos, asi que se requiere un dominio básico de la librería de numpy y pandas.

Vamos a utilizar dos tipos de sets de datos, datos de entrenamiento sobre los que entrenar nuestro algoritmo y un set de test

In [ ]:
CATEGORICAL_COLUMNS = ['sex', 'n_siblings_spouses', 'parch', 'class', 'deck',
                       'embark_town', 'alone']
NUMERIC_COLUMNS = ['age', 'fare']

feature_columns = []
for feature_name in CATEGORICAL_COLUMNS:
  vocabulary = dftrain[feature_name].unique()  # gets a list of all unique values from given feature column
  feature_columns.append(tf.feature_column.categorical_column_with_vocabulary_list(feature_name, vocabulary))

for feature_name in NUMERIC_COLUMNS:
  feature_columns.append(tf.feature_column.numeric_column(feature_name, dtype=tf.float32))

print(feature_columns)

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib

import tensorflow.compat.v2.feature_column as fc

import tensorflow as tf

# Load dataset.
dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv') # training data
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv') # testing data
y_train = dftrain.pop('survived')
y_eval = dfeval.pop('survived')


# Proceso de Entrenamiento 

Una vez hemos selccionado nuestro algoritmo, tenemos que darle los datos al modelo para que pueda procesarlos y extrapolar conclusiones. Los datos se implementan en paquetes de forma automatica (paquetes de 32 datos). El **epoch** es el número de veces que le damos al modelo el mismo paquete de datos para que pueda procesarlos más adelante. Esto es importante ya que las primeras veces que un modelo trata un paquete de datos no va a ser capaz de trabajar de forma adecuada con este. 

Para programar como configuramos los paquetes y los epochs, tenemos que programar una función de input de datos.


In [ ]:
def make_input_fn(data_df, label_df, num_epochs=10, shuffle=True, batch_size=32):
  def input_function():  # inner function, this will be returned
    ds = tf.data.Dataset.from_tensor_slices((dict(data_df), label_df))  # create tf.data.Dataset object with data and its label
    if shuffle:
      ds = ds.shuffle(1000)  # randomize order of data
    ds = ds.batch(batch_size).repeat(num_epochs)  # split dataset into batches of 32 and repeat process for number of epochs
    return ds  # return a batch of the dataset
  return input_function  # return a function object for use

train_input_fn = make_input_fn(dftrain, y_train)  # here we will call the input_function that was returned to us to get a dataset object we can feed to the model
eval_input_fn = make_input_fn(dfeval, y_eval, num_epochs=1, shuffle=False)


# Crear un modelo que manipular

In [22]:
linear_est = tf.estimator.LinearClassifier(feature_columns=feature_columns)
# We create a linear estimtor by passing the feature columns we created earlier

NameError: name 'feature_columns' is not defined

# Entrenar un modelo

In [ ]:
linear_est.train(train_input_fn)  # train
result = linear_est.evaluate(eval_input_fn)  # get model metrics/stats by testing on tetsing data

clear_output()  # clears console output
print(result['accuracy'])  # the result variable is simply a dict of stats about our model